version: '3.7'
services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
  sonarqube:
    image: sonarqube:community
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
  postgres:
    image: postgres:10.5
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    ports:
      - "5432:5432"
volumes:
  postgres-data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
