version: '3.7'
services:
  postgres:
    image: postgres:10.5
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    ports:
      - "5432:5432"
volumes:
  postgres-data:
