spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/userDb?stringtype=unspecified
    username: postgres
    password: 123
  h2:
    console:
      enabled: true
  liquibase:
    enabled: true