server.port: 8765

spring:
  application:
    name: api-gateway

grpc:
  client:
    auth-service:
      address: 'localhost:9090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext


eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


# it can discover other services from eureka
spring.cloud.gateway.discovery.locator.enabled: false
spring.cloud.gateway.discovery.locator.lower-case-service-id: true
