server.port: 8083

spring:
  application:
    name: payment-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/payment_db?stringtype=unspecified
    username: postgres
    password: 123
  jpa:
    show-sql: false
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  liquibase:
    enabled: true

logging:
  level:
    com:
      example: DEBUG