server.port: 8761

spring:
  application:
    name: naming-server
  config:
    import: optional:configserver:http://localhost:8888
  client:
    register-with-eureka: false
    fetch-registry: false
  zipkin:
    base-url: http://localhost:9411/
