spring:
  application:
    name: users-service
  config:
    import: optional:configserver:http://localhost:8888 # TODO agte eureka
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/merchant_db?stringtype=unspecified
    username: postgres
    password: 123
  liquibase:
    enabled: true