server:
  port: 8082

spring:
  application:
    name: merchants-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/merchant_db?stringtype=unspecified
    username: postgres
    password: 123
  jpa:
    show-sql: false
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        integrator_provider: com.example.config.CustomIntegratorProvider
  liquibase:
    enabled: true

